name: "HomeLand"
main: "cn.stevei5mc.homland.HomeLandMain"
version: "${version}"
author: "stevei5mc"
api: ["1.0.14"]

permissions:
  homeland.user:
    description: "插件用户主权限"
    default: true
  homeland.admin:
    description: "插件管理员主权限"
    default: op
  homeland.admin.reload:
    description: "插件管理员重载限"
    default: op