name: pr check
on:
  pull_request:
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      changed_fies: ${{ steps.changed-fies.outputs.all_changed_and_modified_files }}
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      artifact_name: ${{ steps.get_info.outputs.repository_name }}-PR_${{ github.event.pull_request.number }}-Build_${{ github.run_number}}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
    - name: 检查改动文件
      id: changed-fies
      uses: tj-actions/changed-files@v45.0.3
    - name: 输出改动文件
      run: echo ${{ steps.changed-fies.outputs.all_changed_and_modified_files }}
    
            
  build-plugin-body:
    name: Build plugin body
    needs: initialize
    if: contains(needs.initialize.outputs.changed_fies, 'src/') 
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
      with:
        submodules: true
    - name: 安装java8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    # - name: 构建
    #   run: |
    #     mvn -B package --file pom.xml
    #     mkdir staging
    #     cp target/*.jar staging
    # - name: 上传构建
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: ${{ needs.initialize.outputs.artifact_name }}
    #     path: staging

  build-Docusaurus:
    name: Build docusaurus
    needs: initialize
    if: contains(needs.initialize.outputs.changed_fies, 'src/') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      # - name: 安装依赖
      #   run: yarn install --frozen-lockfile
      # - name: 构建网站
      #   run: yarn build
      # - name: 上传构建
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: build