name: pr check
on:
  pull_request:
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      changed_fies: ${{ steps.changed-fies.outputs.all_changed_and_modified_files }}
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      artifact_name: ${{ steps.get_info.outputs.repository_name }}-PR_${{ github.event.pull_request.number }}-Build_${{ github.run_number}}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: 检查改动文件
      id: changed-fies
      uses: tj-actions/changed-files@v45.0.3
    - name: 输出改动文件
      run: echo ${{ steps.changed-fies.outputs.all_changed_and_modified_files }}
    
            
  build-plugin-body:
    name: Build plugin body
    needs: initialize
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkou6t@v4
      with:
        submodules: true
    - name: 安装java8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: 构建
      run: |
        cd plugin-body
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
        cd ../
    - name: 上传构建
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.initialize.outputs.artifact_name }}
        path: plugin-body/staging

  build-Docusaurus:
    name: Build docusaurus
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup nodejs 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: 构建
        run: |
          cd Docusaurus
          npm ci
          npm run build
          cd ../