name: tag push
on:
  push:
    tags:
      - '*'
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_info.outputs.version }}
      repo_name: ${{ steps.get_info.outputs.repo_name }}
      artifact_name: ${{ steps.get_info.outputs.repo_name }}-Release-${{ steps.get_info.outputs.version }}
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT

  build-plugin-body:
    name: Build plugin body
    needs: initialize
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: 安装java8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: 构建
      run: |
        cd plugin-body
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
        cd ../
    - name: 上传构建
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.initialize.outputs.artifact_name }}
        path: plugin-body/staging

  build-Docusaurus:
    name: Build docusaurus
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: 构建
          cd Docusaurus
          npm ci
          npm run build
          cd ../
      - name: 上传构建
        uses: actions/upload-pages-artifact@v3
        with:
          path: Docusaurus/build

  release:
    name: Release
    needs:
    - build-plugin-body
    - build-Docusaurus
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4
    - name: 下载构建
      uses: actions/download-artifact@v4
      with:
        path: staging
        merge-multiple: true
        pattern: ${{ needs.initialize.outputs.repo_name }}-*
    - name: 发布新版本
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ needs.initialize.outputs.version }}
        name: ${{ needs.initialize.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: ./docs/changelogs/${{ needs.initialize.outputs.version }}.md
        artifacts: ./staging/*.*
    #这个暂时没有用
    # - name: 发布至minebbs
    #   uses: engsr6982/upload-minebbs@v1.2.0
    #   with: 
    #     minebbs_token: ${{ secrets.MINEBBS_TOKEN }}
    #     resource_id: "12345"
    #     upload_file: ./github_artifact/*.*
    #     update_title: ${{ needs.initialize.outputs.version }}
    #     update_version: ${{ needs.initialize.outputs.version }}

  deploy-gitHub-pages:
    name: Deploy gitHub pages
    needs: release
    # 给予 GITHUB_TOKEN 进行 Pages 部署所必须的权限
    permissions:
      pages: write # 以部署到 Pages
      id-token: write # 以验证部署来自恰当的源
    # 部署到 Github Pages 环境
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4